# Generated by Django 4.2.2 on 2023-06-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blog', '0004_user_alter_comentario_user_alter_memoria_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(related_name='users_custom', to='auth.group', verbose_name='Grupos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(related_name='users_custom', to='auth.permission', verbose_name='Permisos de usuario'),
        ),
    ]
